### ISSUE TITLE
v1.0.0 is not supporting esm import

### ISSUE THREAD

**Issue by jefftham** [m-radzikowski/aws-sdk-client-mock#99]
**Checklist**

- [ x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

After updating this great library from 0.6.2 to 1.0.0, the test failed because unable to load this library by using esm import.

```
import { mockClient } from 'aws-sdk-client-mock';
         ^^^^^^^^^^
SyntaxError: Named export 'mockClient' not found. The requested module 'aws-sdk-client-mock' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'aws-sdk-client-mock';
const { mockClient } = pkg;

      at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
      at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
      at async Loader.import (internal/modules/esm/loader.js:178:24)

```

**Environment**

- Node version: 
- Testing lib and version:  Mocha
- Typescript version: n/a
- AWS SDK v3 Client mock version: 1.0.0
- AWS JS SDK libs and versions: 
  -  "@aws-sdk/client-dynamodb": "^3.110.0",
  - "@aws-sdk/client-eventbridge": "^3.110.0",
  - "@aws-sdk/client-lambda": "^3.110.0",
  - "@aws-sdk/client-s3": "^3.110.0",
  - "@aws-sdk/client-sns": "^3.110.0",
  - "@aws-sdk/client-sqs": "^3.110.0",
  - "@aws-sdk/lib-dynamodb": "^3.110.0"

**Comment by m-radzikowski** [comment]
Hey. I understand that the issue is with using it with ESM imports with pure JavaScript.

Few notes from my initial investigation (mostly so I have it written down to continue on this later):

1. Removing `exports` section from package.json solves the issue.
    - But we need `exports` due to separating `libStorage` import and "`exports` is a modern alternative to `main`" field so we want to be able to still use it ([docs](https://nodejs.org/api/packages.html#package-entry-points))
2. Adding `type: module` to package.json throws errors `Cannot find module '.../aws-sdk-client-mock-issue99/node_modules/aws-sdk-client-mock/dist/es/mockClient' imported from .../aws-sdk-client-mock-issue99/node_modules/aws-sdk-client-mock/dist/es/index.js`.
    - Those errors are fixed by adding the `.js` extension to imports in ESM files.
    - Those files are generated by `tsc` with `target: ES5`.

I expected ES modules to work the same with just `main` as with `main` and `exports` in package.json. Apparently, I was wrong and Node treats it differently (while TypeScript works fine).

One possible solution could be adding `type: module` and changing generated ESM files to include `.js` extensions in the imports - maybe by bumping up the target version in `tsconfig`. To check:

- will this affect CJS imports?
- will this affect TypeScript usage?

I will try to follow up on this in the next days.

**Comment by davecardwell** [comment]
When using TypeScript’s `"moduleResultion": "NodeNext"` compiler option I see an issue finding the types in `v1.0.0`:

```
$ node_modules/.bin/tsc --noEmit

index.ts:1:28 - error TS7016: Could not find a declaration file for module 'aws-sdk-client-mock'. '/private/tmp/aws-sdk-client-mock-99/node_modules/aws-sdk-client-mock/dist/es/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/aws-sdk-client-mock` if it exists or add a new declaration (.d.ts) file containing `declare module 'aws-sdk-client-mock';`

1 import { mockClient } from "aws-sdk-client-mock";
                             ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in index.ts:1
```

Repro here: https://gist.github.com/davecardwell/e4e18847ebf92532ba966e9a596affa8

This was previously working fine in `v0.6.2` which you can confirm by switching the same repro to use that version.

**Comment by m-radzikowski** [comment]
I've released the [2.0.0-beta.0](https://github.com/m-radzikowski/aws-sdk-client-mock/releases/tag/v2.0.0-beta.0) that should fix the problems. It removes the `mockLibStorageUpload` helper for the `@aws-sdk/lib-storage` which was causing problems. See details in #105.

@jefftham, @davecardwell - please test the v2.0.0-beta.0 if you can and let me know if everything works fine in your workflows.

**Comment by davecardwell** [comment]
Thank you for the quick turnaround on this, @m-radzikowski.

I can confirm that with v2.0.0-beta.1 my type issues go away.

**Comment by jefftham** [comment]
Thanks @m-radzikowski , v2.0.0-beta.1 solved the ESM import problem.

**Comment by tudor33sud** [comment]
Thanks @m-radzikowski . I was having the same problem using jest with esm modules, and now with v2.0.0-beta.1 it's all good.

**Comment by ashshort** [comment]
Thanks @m-radzikowski . This was causing me to scratch my head but now it's all working!
