### ISSUE TITLE
 Typescript errors after upgrading from 0.5.3 to 0.5.4

### ISSUE THREAD

**Issue by sekhavati** [m-radzikowski/aws-sdk-client-mock#50]
**Checklist**

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

Firstly, thank you for making this library available - it's great and much appreciated. 

The issue I'm encountering is that after upgrading 0.5.3 -> 0.5.4 (0.5.3 worked fine). I'm getting typescript errors such as:

```
error TS2339: Property 'Entries' does not exist on type 'ServiceInputTypes'.
Property 'Entries' does not exist on type 'AddPermissionCommandInput'.
94     expect(mockSqsClient.call(0).args[0].input.Entries).toHaveLength(10);
```
```
error TS2339: Property 'QueueUrl' does not exist on type 'ServiceInputTypes'.
Property 'QueueUrl' does not exist on type 'CreateQueueCommandInput'.
104     expect(mockSqsClient.call(2).args[0].input.QueueUrl).toBe(
```

There seems to be some type definitions mix up going on, because in this test I'm actually dealing with a `SendMessageBatchCommandInput` which should have `QueueUrl`/`Entries` available to it. 

In case it helps with diagnosing, I am in a monorepo environment, but all packages have been upgrade to the latest version of their respective SDK deps (ie: `3.31.0` at time of writing) and the _root_ level `package.json` has the following deps declared:

```
 "devDependencies": {
   "@aws-sdk/client-s3": "^3.31.0",
   "@aws-sdk/types": "^3.29.0",
   "aws-sdk-client-mock": "^0.5.4",
 }
``` 

**Environment**

- Node version: `14.17.6`
- Typescript version: `4.4.3`
- AWS SDK v3 Client mock version: `0.5.4`
- AWS JS SDK libs and versions: `3.31.0` (`3.29.0` for `@aws-sdk/types` ie: the latest)

**Comment by m-radzikowski** [comment]
Hey,
I tested it and I'm unable to reproduce the problem. I tried the same versions of dependencies as you listed and this test:

```typescript
import {mockClient} from 'aws-sdk-client-mock';
import {SendMessageBatchCommand, SQSClient} from '@aws-sdk/client-sqs';

const sqsMock = mockClient(SQSClient);

it('mocks sqs', async () => {
    sqsMock
        .on(SendMessageBatchCommand, {
            Entries: [
                {
                    Id: '1',
                    MessageBody: '111',
                }
            ],
            QueueUrl: 'qq',
        })
        .resolves({
            Successful: [{Id: '1', MessageId: '1', MD5OfMessageBody: ''}]
        });

    const sqs = new SQSClient({});

    const result = await sqs.send(new SendMessageBatchCommand({
        Entries: [
            {
                Id: '1',
                MessageBody: '111',
            }
        ],
        QueueUrl: 'qq',
    }));

    expect(result.Successful).toHaveLength(1);
});
```

and it works fine.

I would suggest specifying exact dependency versions for AWS SDK packages (so for example `"@aws-sdk/client-s3": "3.31.0"`, without `^`) to make sure all your packages are in the same version. If this won't help, please create a small repo that with a reproduction of this problem.

**Comment by sekhavati** [comment]
@m-radzikowski thanks for getting back to me. In your example if you added the following assertions do you get any TypeScript errors?

```typescript
expect(sqsMock.call(0).args[0].input.Entries).toHaveLength(1);
expect(sqsMock.call(0).args[0].input.QueueUrl).toBe('qq');
```

I'm in the middle of something else currently but will try what you suggested later this week hopefully if with the above code you still cannot reproduce the error.

**Comment by m-radzikowski** [comment]
Yes, I have type errors on `Entries` and `QueueUrl` with that code added. But I have the same error with mocking lib v0.5.3.

I don't think this is a bug. What you do here is check the arguments of `SQSClient#send()` invocations. While you have full typing support for mocking individual commands (so the lib can match types of expected input and result), the lib (or Sinon that is used under the hood) does not know what type was the first, second, ... command.

When you take `sqsMock.call(0).args[0]` you are getting a type that matches any command that you could pass to `SQSClient#send()`: `AddPermissionCommand`, `ChangeMessageVisibilityCommand`, `ChangeMessageVisibilityBatchCommand`, etc. Because the lib does not know (statically) what command was the first one you executed.

What you need to do is to specify the type by hand:

```typescript
expect((sqsMock.call(0).args[0].input as SendMessageBatchCommandInput).Entries).toHaveLength(1);
```

Again - I don't know how that could work for you before 😄

**Comment by sekhavati** [comment]
@m-radzikowski Thanks again for the response. I've just had a chance to relook at this. In `v0.5.5` this is no longer an issue for me and I haven't had to make any code changes to my tests (the original issue was reported against `v0.5.4`). 

Also thank you for offering a workaround, I'm sure that would have helped had the issue not resolved itself.
