### ISSUE TITLE
Cannot build with Jest 30.3.0

### ISSUE THREAD

**Issue by IKS-Ploetzwich** [m-radzikowski/aws-sdk-client-mock#259]
### Checklist

- [x] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Recently updated project to Jest 30.3.0.
Jest updated to @sinonjs/fake-timers v15. 

This apperently clashes with this repo as I cannot build and get a duplicate idendtifier error:
```TS2300: Duplicate identifier 'withGlobal'```

When introduce @sinonjs/fake-timers v15 to my project dependencies i get new errors cpming from this package:
```
error TS7016: Could not find a declaration file for module 'sinon'. '/[...]/node_modules/sinon/lib/sinon.js' implicitly has an 'any' type.
 If the 'sinon' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/sinon'

3 import type { SinonSpyCall } from 'sinon';
```

When I import the lastest version of @types/sinon I get different errors again:
```
error TS2694: Namespace '"/[...]/node_modules/@sinonjs/fake-timers/types/fake-timers-src"' has no exported member 'FakeTimerInstallOpts'.

1441         useFakeTimers: boolean | Partial<FakeTimers.FakeTimerInstallOpts>;
```

### Reproduction

No code snippet, build issue with dependecies

### Environment

- Node version: v24.x
- Testing lib and version: jest 30.3.0
- Typescript version: 5.9.3
- AWS SDK v3 Client mock version: 4.1.0
- AWS JS SDK libs and versions:
    -  "@aws-sdk/client-dynamodb": "3.1029.0"
    - "@aws-sdk/lib-dynamodb": "3.1029.0"
    - "@aws-sdk/util-dynamodb": "3.996.2"

**Comment by 04kash** [comment]
We encountered a similar issue in Backstage (https://github.com/backstage/backstage/pull/34182). The type incompatibilities have  been fixed in `@types/sinon@21.0.1` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/74827) so updating the sinon dependencies in `aws-sdk-client-mock` to v21.0.1+ should resolve the issue, and I have a PR open for this: https://github.com/m-radzikowski/aws-sdk-client-mock/pull/260
